[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache_forge'
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 1000000
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@v4-periphery/=lib/v4-periphery',
    '@v4-core/=lib/v4-core',
]

[rpc_endpoints]
base = "${BASE_MAINNET_RPC_URL}"
base_testnet = "${BASE_TESTNET_RPC_URL}"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true